site_name: Basic Functions Of C++
theme: material
extra_css:
  - "css/custom-styles.css"
extra_javascript: 
  - "js/extra.js"
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - codehilite
  - mdx_math
pages: 
  - ホーム: index.md
  - PCの仕組み: PCの仕組み.md
  - C++の概要: C++の概要.md
  - 開発環境を整える: 開発環境を整える.md
  - 出力: 出力.md
  - 変数: 変数.md